### ISSUE TITLE
Helpfuctions.cs 

### ISSUE THREAD

**Issue by Kamefrede** [noHero123/silverfish#12]
As title says, the file is missing when i go to build Silverfish in VB2015

**Comment by D-Nice** [comment]
Make sure you read the readme for HR or HearthBuddy.

For HR, you must copy ai and cards folders to the HR directory, and then create an existing project using those 2 folders and program.cs inside HR folder.

**Comment by Kamefrede** [comment]
I'm a bit confused by all of this, since this is my first time doing anything in Visual studio, how would i go about of creating a project with those 2 folders and program.cs?

**Comment by Kamefrede** [comment]
Okay, i think i did it but, i got some warnings and i'm not sure if it will work properly or not

1>------ Build started: Project: Silver, Configuration: Debug Any CPU ------
1>C:\Users\User\Desktop\Silverfish\cards\Sim__AT_022.cs(25,29,25,46): warning CS0114: 'Sim_AT_022.onCardIsDiscarded(Playfield, CardDB.Card, bool)' hides inherited member 'SimTemplate.onCardIsDiscarded(Playfield, CardDB.Card, bool)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.
1>C:\Users\User\Desktop\Silverfish\ai\ComboBreaker.cs(52,21,52,22): warning CS0219: The variable 'i' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\ai\CardDB.cs(6022,17,6022,19): warning CS0219: The variable 'de' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\Program.cs(556,17,556,25): warning CS0219: The variable 'totalwin' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\Program.cs(557,17,557,26): warning CS0219: The variable 'totallose' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\Program.cs(598,13,598,19): warning CS0162: Unreachable code detected
1>C:\Users\User\Desktop\Silverfish\ai\CardDB.cs(5877,22,5877,28): warning CS0219: The variable 'retval' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\ai\PenalityManager.cs(755,17,755,20): warning CS0219: The variable 'pen' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\cards\Sim_CS2_049.cs(70,18,70,33): warning CS0219: The variable 'spawnspellpower' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\ai\Playfield.cs(1402,22,1402,30): warning CS0219: The variable 'dontkill' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\ai\MiniSimulator.cs(15,22,15,32): warning CS0414: The field 'MiniSimulator.dontRecalc' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\ai\Ai.cs(19,22,19,35): warning CS0414: The field 'Ai.useComparison' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\Program.cs(68,24,68,36): warning CS0414: The field 'Bot.choiceCardId' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\ai\MiniSimulatorNextTurn.cs(17,22,17,32): warning CS0414: The field 'MiniSimulatorNextTurn.dontRecalc' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\ai\Ai.cs(15,22,15,40): warning CS0414: The field 'Ai.usePenalityManager' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\Program.cs(67,21,67,32): warning CS0414: The field 'Bot.dirtychoice' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\Program.cs(969,13,969,23): warning CS0414: The field 'Silverfish.enemyPrepa' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\Program.cs(967,13,967,26): warning CS0414: The field 'Silverfish.enemyKirintor' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\Program.cs(66,21,66,32): warning CS0414: The field 'Bot.dirtytarget' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\ai\MiniSimulatorNextTurn.cs(18,22,18,36): warning CS0414: The field 'MiniSimulatorNextTurn.useLethalCheck' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\ai\Ai.cs(16,22,16,38): warning CS0414: The field 'Ai.useCutingTargets' is assigned but its value is never used
1>C:\Users\User\Desktop\Silverfish\ai\MiniSimulator.cs(16,22,16,36): warning CS0414: The field 'MiniSimulator.useLethalCheck' is assigned but its value is never used
1>  Silver -> C:\Users\User\Desktop\Silverfish\bin\Debug\ClassLibrary.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by Kamefrede** [comment]
I think something went wrong because the bot does nothing, just fiddles arround with the cards.

I paired it with Silver.exe

**Comment by D-Nice** [comment]
don't pair it with silver.exe, use just the .dll first

Warnings aren't problematic, errors are though.

To use it with silver.exe, you also need to compile the same version of silver.exe, you can't use a random silver.exe.

**Comment by Kamefrede** [comment]
I see, how would i go about compiling silver.exe

**Comment by D-Nice** [comment]
Do baby steps, compile the .dll first, and set useexternalprocess to false in the settings file.

To compile the .exe, you would need to paste the Program.cs, from the external process folder and use that instead of the one from HR.

**Comment by D-Nice** [comment]
Why don't you simply use the silver.dll and silver.exe provided here, or are you modifying parts of it and trying to compile???

**Comment by Kamefrede** [comment]
I'm not trying to modify it i was just experimenting with compiling

**Comment by noHero123** [comment]
Helpfuctions.cs is needed from defaultroutine of Hearthbuddy.. i just updated HB-version + instruction
(works for me)
