### ISSUE TITLE
Not doing 'obvious' lethal irregardless of maxWide

### ISSUE THREAD

**Issue by D-Nice** [noHero123/silverfish#14]
I saw this lethal immediately, yet the bot, even after setting it to insane maxWides, fails to find this clear lethal, so it must be a bug somewhere. I'm having a look for it, but let me know if anyone else has luck. The only time the bot finds the lethal is if I disable everything BUT maxwide.

Here's the log file, which can be used in a test.txt with silver.exe to test outcome.

#######################################################################
start calculations, current time: 12:00:00:3930 V116.00 control 20000 face 15 twoturnsim 1000 ntss 6 200 200 ets 50 ets2 200 ents 100 secret plcmnt
#######################################################################
mana 8/8
emana 7
own secretsCount: 0
enemy secretsCount: 0 ;
player:
0 0 0 2 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0
ownhero:
shaman 25 30 0 False False 36 True 0 False 0 0
weapon: 0 0 unknown
ability: True CS2_049 1
osecrets: 
enemyhero:
warlock 11 30 0 False False 4
weapon: 0 0 unknown
ability: True CS2_056 0
fatigue: 19 0 17 0
OwnMinions:
pilotedshredder GVG_096 zp:1 e:39 A:4 H:3 mH:3 rdy:True natt:0
wrathofairtotem CS2_052 zp:2 e:84 A:0 H:2 mH:2 rdy:True natt:0
EnemyMinions:
nerubianegg FP1_007 zp:1 e:24 A:0 H:2 mH:2 rdy:False natt:0 ex ptt
spectralspider FP1_002t zp:2 e:82 A:1 H:1 mH:1 rdy:True natt:0 ex
spectralspider FP1_002t zp:3 e:81 A:1 H:1 mH:1 rdy:True natt:0 ex
nerubianegg FP1_007 zp:4 e:6 A:0 H:2 mH:2 rdy:True natt:0
imp GVG_045t zp:5 e:88 A:1 H:1 mH:1 rdy:False natt:0 ex ptt
imp GVG_045t zp:6 e:89 A:1 H:1 mH:1 rdy:False natt:0 ex ptt
Own Handcards: 
pos 1 lightningstorm 3 entity 41 EX1_259 0 0
pos 2 bloodlust 5 entity 54 CS2_046 0 0
pos 3 hex 3 entity 46 EX1_246 0 0
pos 4 flametonguetotem 2 entity 67 EX1_565 0 0
Enemy cards: 3
ownDiedMinions: 
enemyDiedMinions: 
og: 422,1;981,1;980,2;994,1;557,1;
eg: 1205,2;823,1;661,1;557,1;981,2;301,1;

**Comment by D-Nice** [comment]
The obvious lethal is to set flametongue down between shredder and air totem, and then bloodlusting.

**Comment by noHero123** [comment]
will be fixed in next version
