### ISSUE TITLE
Changing passed parameter in penalitymanager

### ISSUE THREAD

**Issue by D-Nice** [noHero123/silverfish#15]
I noticed you changed the first parameter from CardDB.Card to Handmanager.Handcard, for reasons of getting the minion cost passed to the other penality functions. I had this same issue, and was going to do the same thing, but wouldn't this work just as well for CardDB:

card.getManaCost(p, card.cost) 

Variable card is obviously a CardDB.Card and p = playfield. This should give the appropriate cost of the card in the hand, should it not? As card.cost passes the cost of the card from _carddb, and then passing playfield, allows it to calculate the current cost of it in your hand, so you didn't need to change the variables passed into penality manager. I didn't initially want to change them, to try and keep the code and methods as close to yours as possible.

I needed the cost for a number of things in penality, such as this piece of code

        private int getLessCostBonus(CardDB.Card card, Playfield p) //Should play dread corsair and other cost less more often when their costs are lower
        {
            int bonus = 0;

            if (card.getManaCost(p, card.cost) < card.cost) bonus = (card.getManaCost(p, card.cost) - card.cost) * 5;

            return bonus;
        }

As I noticed, Dread Corsair, and other minions, were not being played, even if their cost was 0.

**Comment by noHero123** [comment]
card.getManaCost(p, card.cost)  with card.cost from the carddb will only give correct results, whether the card has his orginal costs, or his costs are changed in such a way, that the orginal costs can be recalculated. this is not the case with effects on that card like "freezing trap". thats why i took the Handmanager.Handcard.

**Comment by D-Nice** [comment]
Ah I see, thanks for the clarification.
