### ISSUE TITLE
Bot not following cast position set

### ISSUE THREAD

**Issue by D-Nice** [noHero123/silverfish#21]
I have the following line of code directly under the getBestPlace function in Playfield.cs, as the first line of code.

if (card.name == CardDB.cardName.tuskarrtotemic)
{
      return 1;
}

My hope with this was to always make sure Tuskarr Totemic is cast to the left of minions on your board. However, no matter what number I return, it always casts Tuskarr rightmost of all minions. I've checked the logs, and it is in fact passing the correct position, but either Hearthranger or something just isn't properly casting it.

Here's a short console log

#ConsoleLog: playcard: Tuskarr Totemic target nothing choice: 0 place1
#ConsoleLog: updateEverything
#ConsoleLog: 11 .AT_046. tuskarrtotemic ready params ex: True charge: 0 attcksthisturn: 0 playedthisturn True
#ConsoleLog: 20 .AT_052. totemgolem ready params ex: False charge: 0 attcksthisturn: 0 playedthisturn False
#ConsoleLog: 69 .CS2_051. stoneclawtotem ready params ex: True charge: 0 attcksthisturn: 0 playedthisturn True

**Comment by noHero123** [comment]
jeah, I'm aware of this bug of HearthRanger. talked with JoyAdmin about it last days (thats the reason of https://github.com/noHero123/silverfish/tree/master/external%20process/placement_test it is placing the minions allways at position 1)
